version: '3.1'

services:
  mariadb:
    container_name: mariadb
    build: /home/{{ ansible_user }}/mariadb
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    networks:
      - web
    restart: always

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/{{ ansible_user }}/data/db

networks:
  web:
