---
- name: Install necessary dependencies
  apt:
    name: ['software-properties-common', 'ca-certificates', 'curl']
    state: present
    update_cache: yes

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Add the Docker repository to Apt sources
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    update_cache: yes

- name: Install docker
  apt:
    name: ['docker.io', 'docker-compose', 'docker-compose-plugin']
    state: present
    update_cache: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create root working directory
  file:
    path: /home/{{ ansible_user }}/cloud
    state: directory

- name: Create working directorys
  file:
    path: /home/{{ ansible_user }}/cloud/{{ item }}
    state: directory      
  with_items:
    - mariadb
    - wordpress
    - nginx